### PR TITLE
Remove unneeded labels

### PR DESCRIPTION
**Pull request by micbar**

### CODE REVIEW

**Comment by micbar** [comment]
@refs You inspired me to go with the big solution.

still need to find adequate colors

**Comment by refs** [comment]
> @refs You inspired me to go with the big solution.
> 
> 
> 
> still need to find adequate colors

Thanks! Didn't really want to pull you in too deep!

**Comment by micbar** [comment]
@refs let us merge now here and care about the colors in a second pr

**Comment by refs** [comment]
> @refs let us merge now here and care about the colors in a second pr

aww I thought we wanted to set the record straight. Let's merge, move on and add colors later.

**Review by refs — APPROVED** [review]

**Pull request merged**
